---
---

<br>

<font color="#218cba"><b>05/2017 - Present</font> &emsp;&nbsp; Data Analyst, Analytics Department,
[Intelen Inc, Athens](https://intelen.com/us/)</b>

* Design, develop and maintain analytics app (R Shiny) for the following purposes: 
data visualisation, statistical results, simulation, KPI monitoring, customer scoring & segmentation, predictive modelling, etc.
* Use supervised and unsupervised machine learning methods to optimize customer experience, revenue generation and other business outcomes
* Enhance customer experience building recommender systems for personalized services
* Develop and automate reporting processes
* Define, measure and monitor KPIs
* Design new data-driven business products

<font color="#218cba"><b>07/2016 - 05/2017</font> &emsp; Data Scientist, Credit Risk Department, [ICAP Group, Athens](https://www.icap.gr/)</b>

* Prepare the thesis "Storage of Default Characterization Data", as part of the M.Sc. in Business Analytics, Athens University of Economics and Business  
* Support regulatory requirements on reporting and monitoring of ICAP's credit assessment evolution data to regulators
* Support reporting to European Rating Platform (ERP/RADAR), the platform maintained by ESMA on credit rating agencies data
* Design, develop and maintain statistical procedures and tools (automated and semi-automated procedures) for the monitoring of credit assessment evolution in SAS and R softwares, as well as, data management and automation activities
* Business process modelling

<font color="#218cba"><b>01/2015 – 10/2015</font> &emsp; Researcher, Telephone Research Department, [Metron Analysis S.A., Athens](https://www.metronanalysis.gr/)</b> 

* Participate in the conduction of various research projects in the section of the telephone survey department.<br> 
